apiVersion: v1
kind: Service
metadata:
  name: front-end-service
spec:
  selector:
    app: Pfe-front-end
    tier: frontend
    env: prod
  ports:
   - name: test
      protocol: "TCP"
      port: 80
      targetPort: 80
   type: LoadBalancer
