apiVersion: v1
kind: Service
metadata:
  name: FrontEnd
spec:
  selector:
    app: Pfe-front-end
    env: prod
  ports:
    - name: test
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 32200  # Specify the NodePort here
  type: NodePort  # Change the service type to NodePort
