name: NodeJS with Gulp

on:
 push:
   branches: [ "master" ]
 pull_request:
   branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.21.3]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm install
        
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Build and Push Docker image
      run: |
        docker build -t jacino/devops:frontend01 .
        docker push jacino/devops:frontend01
        
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Verify K8s Service Account
      uses: azure/setup-kubectl@v3
    - name: Create/Verify `.kube` directory
      run: mkdir -p ~/.kube/
    - name: Create kubectl config
      run: |
          cat << EOF >> ~/.kube/kubeconfig.yaml
          ${{ secrets.KUBECONFIG_SA }}
          EOF
    - name: Deploy to Kubernetes
      run: |
          KUBECONFIG=~/.kube/kubeconfig.yaml kubectl delete deployment test-deployments-front -n apps --ignore-not-found=true
          KUBECONFIG=~/.kube/kubeconfig.yaml kubectl delete service front-end-service -n apps --ignore-not-found=true
          KUBECONFIG=~/.kube/kubeconfig.yaml kubectl apply -f deployment.yml
          KUBECONFIG=~/.kube/kubeconfig.yaml kubectl apply -f service.yml
